// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package async

import (
	"context"
	"sync"
)

type ReturnOfBool struct {
	Context context.Context
	Value   bool
	Error   error
}

var pool_of_ReturnOfBool = sync.Pool{
	New: func() interface{} {
		return &ReturnOfBool{}
	},
}

func GetReturnOfBool() *ReturnOfBool {
	return pool_of_ReturnOfBool.Get().(*ReturnOfBool)
}
func PutReturnOfBool(d *ReturnOfBool) {
	pool_of_ReturnOfBool.Put(d)
}

type ReturnOfByte struct {
	Context context.Context
	Value   byte
	Error   error
}

var pool_of_ReturnOfByte = sync.Pool{
	New: func() interface{} {
		return &ReturnOfByte{}
	},
}

func GetReturnOfByte() *ReturnOfByte {
	return pool_of_ReturnOfByte.Get().(*ReturnOfByte)
}
func PutReturnOfByte(d *ReturnOfByte) {
	pool_of_ReturnOfByte.Put(d)
}

type ReturnOfComplex128 struct {
	Context context.Context
	Value   complex128
	Error   error
}

var pool_of_ReturnOfComplex128 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfComplex128{}
	},
}

func GetReturnOfComplex128() *ReturnOfComplex128 {
	return pool_of_ReturnOfComplex128.Get().(*ReturnOfComplex128)
}
func PutReturnOfComplex128(d *ReturnOfComplex128) {
	pool_of_ReturnOfComplex128.Put(d)
}

type ReturnOfComplex64 struct {
	Context context.Context
	Value   complex64
	Error   error
}

var pool_of_ReturnOfComplex64 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfComplex64{}
	},
}

func GetReturnOfComplex64() *ReturnOfComplex64 {
	return pool_of_ReturnOfComplex64.Get().(*ReturnOfComplex64)
}
func PutReturnOfComplex64(d *ReturnOfComplex64) {
	pool_of_ReturnOfComplex64.Put(d)
}

type ReturnOfError struct {
	Context context.Context
	Value   error
	Error   error
}

var pool_of_ReturnOfError = sync.Pool{
	New: func() interface{} {
		return &ReturnOfError{}
	},
}

func GetReturnOfError() *ReturnOfError {
	return pool_of_ReturnOfError.Get().(*ReturnOfError)
}
func PutReturnOfError(d *ReturnOfError) {
	pool_of_ReturnOfError.Put(d)
}

type ReturnOfFloat32 struct {
	Context context.Context
	Value   float32
	Error   error
}

var pool_of_ReturnOfFloat32 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfFloat32{}
	},
}

func GetReturnOfFloat32() *ReturnOfFloat32 {
	return pool_of_ReturnOfFloat32.Get().(*ReturnOfFloat32)
}
func PutReturnOfFloat32(d *ReturnOfFloat32) {
	pool_of_ReturnOfFloat32.Put(d)
}

type ReturnOfFloat64 struct {
	Context context.Context
	Value   float64
	Error   error
}

var pool_of_ReturnOfFloat64 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfFloat64{}
	},
}

func GetReturnOfFloat64() *ReturnOfFloat64 {
	return pool_of_ReturnOfFloat64.Get().(*ReturnOfFloat64)
}
func PutReturnOfFloat64(d *ReturnOfFloat64) {
	pool_of_ReturnOfFloat64.Put(d)
}

type ReturnOfInt struct {
	Context context.Context
	Value   int
	Error   error
}

var pool_of_ReturnOfInt = sync.Pool{
	New: func() interface{} {
		return &ReturnOfInt{}
	},
}

func GetReturnOfInt() *ReturnOfInt {
	return pool_of_ReturnOfInt.Get().(*ReturnOfInt)
}
func PutReturnOfInt(d *ReturnOfInt) {
	pool_of_ReturnOfInt.Put(d)
}

type ReturnOfInt16 struct {
	Context context.Context
	Value   int16
	Error   error
}

var pool_of_ReturnOfInt16 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfInt16{}
	},
}

func GetReturnOfInt16() *ReturnOfInt16 {
	return pool_of_ReturnOfInt16.Get().(*ReturnOfInt16)
}
func PutReturnOfInt16(d *ReturnOfInt16) {
	pool_of_ReturnOfInt16.Put(d)
}

type ReturnOfInt32 struct {
	Context context.Context
	Value   int32
	Error   error
}

var pool_of_ReturnOfInt32 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfInt32{}
	},
}

func GetReturnOfInt32() *ReturnOfInt32 {
	return pool_of_ReturnOfInt32.Get().(*ReturnOfInt32)
}
func PutReturnOfInt32(d *ReturnOfInt32) {
	pool_of_ReturnOfInt32.Put(d)
}

type ReturnOfInt64 struct {
	Context context.Context
	Value   int64
	Error   error
}

var pool_of_ReturnOfInt64 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfInt64{}
	},
}

func GetReturnOfInt64() *ReturnOfInt64 {
	return pool_of_ReturnOfInt64.Get().(*ReturnOfInt64)
}
func PutReturnOfInt64(d *ReturnOfInt64) {
	pool_of_ReturnOfInt64.Put(d)
}

type ReturnOfInt8 struct {
	Context context.Context
	Value   int8
	Error   error
}

var pool_of_ReturnOfInt8 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfInt8{}
	},
}

func GetReturnOfInt8() *ReturnOfInt8 {
	return pool_of_ReturnOfInt8.Get().(*ReturnOfInt8)
}
func PutReturnOfInt8(d *ReturnOfInt8) {
	pool_of_ReturnOfInt8.Put(d)
}

type ReturnOfRune struct {
	Context context.Context
	Value   rune
	Error   error
}

var pool_of_ReturnOfRune = sync.Pool{
	New: func() interface{} {
		return &ReturnOfRune{}
	},
}

func GetReturnOfRune() *ReturnOfRune {
	return pool_of_ReturnOfRune.Get().(*ReturnOfRune)
}
func PutReturnOfRune(d *ReturnOfRune) {
	pool_of_ReturnOfRune.Put(d)
}

type ReturnOfString struct {
	Context context.Context
	Value   string
	Error   error
}

var pool_of_ReturnOfString = sync.Pool{
	New: func() interface{} {
		return &ReturnOfString{}
	},
}

func GetReturnOfString() *ReturnOfString {
	return pool_of_ReturnOfString.Get().(*ReturnOfString)
}
func PutReturnOfString(d *ReturnOfString) {
	pool_of_ReturnOfString.Put(d)
}

type ReturnOfUint struct {
	Context context.Context
	Value   uint
	Error   error
}

var pool_of_ReturnOfUint = sync.Pool{
	New: func() interface{} {
		return &ReturnOfUint{}
	},
}

func GetReturnOfUint() *ReturnOfUint {
	return pool_of_ReturnOfUint.Get().(*ReturnOfUint)
}
func PutReturnOfUint(d *ReturnOfUint) {
	pool_of_ReturnOfUint.Put(d)
}

type ReturnOfUint16 struct {
	Context context.Context
	Value   uint16
	Error   error
}

var pool_of_ReturnOfUint16 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfUint16{}
	},
}

func GetReturnOfUint16() *ReturnOfUint16 {
	return pool_of_ReturnOfUint16.Get().(*ReturnOfUint16)
}
func PutReturnOfUint16(d *ReturnOfUint16) {
	pool_of_ReturnOfUint16.Put(d)
}

type ReturnOfUint32 struct {
	Context context.Context
	Value   uint32
	Error   error
}

var pool_of_ReturnOfUint32 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfUint32{}
	},
}

func GetReturnOfUint32() *ReturnOfUint32 {
	return pool_of_ReturnOfUint32.Get().(*ReturnOfUint32)
}
func PutReturnOfUint32(d *ReturnOfUint32) {
	pool_of_ReturnOfUint32.Put(d)
}

type ReturnOfUint64 struct {
	Context context.Context
	Value   uint64
	Error   error
}

var pool_of_ReturnOfUint64 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfUint64{}
	},
}

func GetReturnOfUint64() *ReturnOfUint64 {
	return pool_of_ReturnOfUint64.Get().(*ReturnOfUint64)
}
func PutReturnOfUint64(d *ReturnOfUint64) {
	pool_of_ReturnOfUint64.Put(d)
}

type ReturnOfUint8 struct {
	Context context.Context
	Value   uint8
	Error   error
}

var pool_of_ReturnOfUint8 = sync.Pool{
	New: func() interface{} {
		return &ReturnOfUint8{}
	},
}

func GetReturnOfUint8() *ReturnOfUint8 {
	return pool_of_ReturnOfUint8.Get().(*ReturnOfUint8)
}
func PutReturnOfUint8(d *ReturnOfUint8) {
	pool_of_ReturnOfUint8.Put(d)
}

type ReturnOfUintptr struct {
	Context context.Context
	Value   uintptr
	Error   error
}

var pool_of_ReturnOfUintptr = sync.Pool{
	New: func() interface{} {
		return &ReturnOfUintptr{}
	},
}

func GetReturnOfUintptr() *ReturnOfUintptr {
	return pool_of_ReturnOfUintptr.Get().(*ReturnOfUintptr)
}
func PutReturnOfUintptr(d *ReturnOfUintptr) {
	pool_of_ReturnOfUintptr.Put(d)
}

type ReturnOfBytes struct {
	Context context.Context
	Value   Bytes
	Error   error
}

var pool_of_ReturnOfBytes = sync.Pool{
	New: func() interface{} {
		return &ReturnOfBytes{}
	},
}

func GetReturnOfBytes() *ReturnOfBytes {
	return pool_of_ReturnOfBytes.Get().(*ReturnOfBytes)
}
func PutReturnOfBytes(d *ReturnOfBytes) {
	pool_of_ReturnOfBytes.Put(d)
}

type ReturnOfInterface struct {
	Context context.Context
	Value   interface{}
	Error   error
}

var pool_of_ReturnOfInterface = sync.Pool{
	New: func() interface{} {
		return &ReturnOfInterface{}
	},
}

func GetReturnOfInterface() *ReturnOfInterface {
	return pool_of_ReturnOfInterface.Get().(*ReturnOfInterface)
}
func PutReturnOfInterface(d *ReturnOfInterface) {
	pool_of_ReturnOfInterface.Put(d)
}
