// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package async

type ReturnOfBytes struct {
	Value Bytes
	Error error
}

type ReturnOfString struct {
	Value string
	Error error
}

type ReturnOfInterface struct {
	Value interface{}
	Error error
}
