// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package async

import "context"

type WorkOfBytesThenBytes struct {
	Argument Bytes
	ReturnCh chan<- *ReturnOfBytes
}

type WorkWithContextOfBytesThenBytes struct {
	context.Context
	*WorkOfBytesThenBytes
}

type WorkerOfCallBytesThenBytes interface {
	Call(context.Context, Bytes) (Bytes, error)
}

type WorkerOfPushBytesThenBytes interface {
	Push(context.Context, *WorkOfBytesThenBytes)
}

type WorkOfBytesThenString struct {
	Argument Bytes
	ReturnCh chan<- *ReturnOfString
}

type WorkWithContextOfBytesThenString struct {
	context.Context
	*WorkOfBytesThenString
}

type WorkerOfCallBytesThenString interface {
	Call(context.Context, Bytes) (string, error)
}

type WorkerOfPushBytesThenString interface {
	Push(context.Context, *WorkOfBytesThenString)
}

type WorkOfBytesThenInterface struct {
	Argument Bytes
	ReturnCh chan<- *ReturnOfInterface
}

type WorkWithContextOfBytesThenInterface struct {
	context.Context
	*WorkOfBytesThenInterface
}

type WorkerOfCallBytesThenInterface interface {
	Call(context.Context, Bytes) (interface{}, error)
}

type WorkerOfPushBytesThenInterface interface {
	Push(context.Context, *WorkOfBytesThenInterface)
}

type WorkOfStringThenBytes struct {
	Argument string
	ReturnCh chan<- *ReturnOfBytes
}

type WorkWithContextOfStringThenBytes struct {
	context.Context
	*WorkOfStringThenBytes
}

type WorkerOfCallStringThenBytes interface {
	Call(context.Context, string) (Bytes, error)
}

type WorkerOfPushStringThenBytes interface {
	Push(context.Context, *WorkOfStringThenBytes)
}

type WorkOfStringThenString struct {
	Argument string
	ReturnCh chan<- *ReturnOfString
}

type WorkWithContextOfStringThenString struct {
	context.Context
	*WorkOfStringThenString
}

type WorkerOfCallStringThenString interface {
	Call(context.Context, string) (string, error)
}

type WorkerOfPushStringThenString interface {
	Push(context.Context, *WorkOfStringThenString)
}

type WorkOfStringThenInterface struct {
	Argument string
	ReturnCh chan<- *ReturnOfInterface
}

type WorkWithContextOfStringThenInterface struct {
	context.Context
	*WorkOfStringThenInterface
}

type WorkerOfCallStringThenInterface interface {
	Call(context.Context, string) (interface{}, error)
}

type WorkerOfPushStringThenInterface interface {
	Push(context.Context, *WorkOfStringThenInterface)
}

type WorkOfInterfaceThenBytes struct {
	Argument interface{}
	ReturnCh chan<- *ReturnOfBytes
}

type WorkWithContextOfInterfaceThenBytes struct {
	context.Context
	*WorkOfInterfaceThenBytes
}

type WorkerOfCallInterfaceThenBytes interface {
	Call(context.Context, interface{}) (Bytes, error)
}

type WorkerOfPushInterfaceThenBytes interface {
	Push(context.Context, *WorkOfInterfaceThenBytes)
}

type WorkOfInterfaceThenString struct {
	Argument interface{}
	ReturnCh chan<- *ReturnOfString
}

type WorkWithContextOfInterfaceThenString struct {
	context.Context
	*WorkOfInterfaceThenString
}

type WorkerOfCallInterfaceThenString interface {
	Call(context.Context, interface{}) (string, error)
}

type WorkerOfPushInterfaceThenString interface {
	Push(context.Context, *WorkOfInterfaceThenString)
}

type WorkOfInterfaceThenInterface struct {
	Argument interface{}
	ReturnCh chan<- *ReturnOfInterface
}

type WorkWithContextOfInterfaceThenInterface struct {
	context.Context
	*WorkOfInterfaceThenInterface
}

type WorkerOfCallInterfaceThenInterface interface {
	Call(context.Context, interface{}) (interface{}, error)
}

type WorkerOfPushInterfaceThenInterface interface {
	Push(context.Context, *WorkOfInterfaceThenInterface)
}
